#env GOOS=linux GOARCH=amd64 go build
#docker build -t mercurius:testemercurius .
#docker run -p 8080:8080 -d mercurius:testemercurius

FROM scratch

ADD testemercurius /
ADD conf/ /conf
ADD public/ /public
ADD locale/ /locale

CMD [ "/testemercurius" ]